/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JskZDb4lJ7g
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"

export function WebinarRegistrationTYG() {
  return (
    <section className="w-full max-w-md mx-auto py-12 md:py-24">
      <div className="space-y-4">
        <h1 className="text-3xl font-bold">Webinar Registration</h1>
        <p className="text-gray-500 dark:text-gray-400">
          Learn how to use Voice AI to create and perform better mystery shops.
        </p>
      </div>
      <form className="mt-8 space-y-4">
        <div className="grid gap-4">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input id="name" placeholder="Enter your name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="Enter your email" type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="company">Company</Label>
            <Input id="company" placeholder="Enter your company" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="role">Role</Label>
            <Input id="role" placeholder="Enter your role" />
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <Checkbox id="terms" />
          <Label htmlFor="terms">
            I agree to the
            <Link className="underline" href="#">
              terms and conditions
            </Link>
          </Label>
        </div>
        <Button className="w-full" type="submit">
          Register
        </Button>
      </form>
      <div className="mt-8">
        <div className="bg-gray-100 p-6 rounded-lg dark:bg-gray-800">
          <blockquote className="text-lg font-semibold leading-snug">
            "The webinar was incredibly informative and has helped me transform my mystery shopping process. Highly
            recommended!"
          </blockquote>
          <div className="flex items-center mt-4">
            <Avatar className="w-10 h-10 border">
              <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
            <div className="ml-4">
              <div className="font-semibold">Sarah Johnson</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">Mystery Shopper, Acme Inc</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
